sudo: required
dist: trusty
language: bash

before_install:
    - sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
    - sudo apt-get -qq update
    - sudo apt-get -t trusty-backports install shellcheck
    - sudo pip install bashate

script:
- shellcheck -x aws-useradd.sh
- shellcheck -x aws-useradd.sh
- shellcheck -x aws-datapipeline-monitor.sh
- shellcheck -x aws-ebs-daily-monitor.sh
- shellcheck -x aws-extract-iam-policies.sh
- shellcheck -x aws-lambda-monitor.sh
- shellcheck -x aws-long-running-ec2.sh